Repository IT-Contest/it-contest-fe, pull requests merged in 2025-09, with the labels that each got.

#27 feat: connect profile page API
  lib/features/mainpage/view/profile_page_widget.dart
  lib/features/profile/service/kakao_account_logout_page.dart
  lib/features/profile/view/account_settings_page.dart
  lib/features/profile/view/alarm_list_page.dart
  lib/features/profile/view/notification_settings_page.dart
Labels: :star: feat

#38 분석화면 ui, gpt 응답, 리더보드 ui 수정
  .DS_Store
  lib/core/network/dio_client.dart
  lib/features/analysis/model/analysis_models.dart
  lib/features/analysis/service/analysis_service.dart
  lib/features/analysis/view/analysis_screen.dart
  lib/features/quest/view/daily_quest_fullpage.dart
  lib/features/quest/view/quest_search_screen.dart
  lib/features/quest/view/widgets/quest_list_section.dart
  lib/features/quest/viewmodel/daily_quest_viewmodel.dart
  lib/features/quest/viewmodel/quest_tab_viewmodel.dart
Labels: :wrench:chore

#40 ui QA 반영
  .idea/misc.xml
  lib/core/network/dio_client.dart
  lib/features/analysis/service/analysis_service.dart
  lib/features/analysis/view/analysis_screen.dart
  lib/features/analysis/viewmodel/analysis_viewmodel.dart
  lib/features/quest/view/daily_quest_fullpage.dart
  lib/features/quest/view/quest_search_screen.dart
  lib/features/quest/view/widgets/quest_add_section.dart
  lib/shared/quest_create_form/sub_screen/time_range_picker.dart
Labels: :wrench:chore

#43 프로필 경험치 적용되도록 수정, 퀘스트 삭제 모달 추가
  .idea/libraries/Dart_SDK.xml
  .idea/misc.xml
  .idea/vcs.xml
  lib/core/network/dio_client.dart
  lib/features/mainpage/model/mainpage_user_response.dart
  lib/features/mainpage/service/mainpage_service.dart
  lib/features/mainpage/view/widgets/user_profile_card.dart
  lib/features/mainpage/viewmodel/mainpage_viewmodel.dart
  lib/features/onboarding/viewmodel/onboarding_viewmodel.dart
  lib/features/quest/model/quest_create_request.dart
  lib/features/quest/service/quest_service.dart
  lib/features/quest/view/daily_quest_fullpage.dart
  lib/features/quest/view/quest_personal_view_screen.dart
  lib/features/quest/view/quest_search_screen.dart
  lib/features/quest/view/widgets/quest_list_section.dart
  lib/features/quest/viewmodel/quest_personal_create_viewmodel.dart
  lib/features/quest/viewmodel/quest_tab_viewmodel.dart
  lib/shared/widgets/quest_completion_modal.dart
  lib/shared/widgets/quest_delete_confirmation_modal.dart
  lib/shared/widgets/quest_delete_success_modal.dart
Labels: :wrench:chore

#46 분석탭 qa 반영
  lib/core/network/dio_client.dart
  lib/features/analysis/service/analysis_service.dart
  lib/features/analysis/view/analysis_screen.dart
  lib/features/analysis/viewmodel/analysis_viewmodel.dart
Labels: :wrench:chore

#47 feat/chore: 파티 초대장, 푸시 메시지 추가 및 온보딩 수정
  android/app/src/main/AndroidManifest.xml
  lib/core/network/dio_client.dart
  lib/features/friends/model/friend_info.dart
  lib/features/mainpage/view/home_page_widget.dart
  lib/features/onboarding/view/onboarding_screen.dart
  lib/features/quest/model/party_status_change_response.dart
  lib/features/quest/service/party_service.dart
  lib/features/quest/view/daily_quest_fullpage.dart
  lib/features/quest/view/party_join_page.dart
  lib/features/quest/view/party_quest_view_screen.dart
  lib/features/quest/view/quest_personal_view_screen.dart
  lib/features/quest/view/widgets/quest_card.dart
  lib/features/quest/view/widgets/quest_list_section.dart
  lib/features/quest/viewmodel/quest_tab_viewmodel.dart
  lib/features/terms/view/terms_detail_screen.dart
  lib/shared/alarm/widgets/party_invitation_card.dart
  lib/shared/alarm/widgets/party_push_message.dart
Labels: :star: feat, :wrench:chore

#49 feat: 알림 추가
  .idea/libraries/Dart_SDK.xml
  .idea/misc.xml
  .idea/vcs.xml
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  lib/core/fcm/fcm_service.dart
  lib/core/fcm/fcm_token_api.dart
  lib/core/network/dio_client.dart
  lib/features/auth/service/guest_login_service.dart
  lib/features/auth/service/kakao_login_service.dart
  lib/features/friends/model/friend_info.dart
  lib/features/terms/view/terms_detail_screen.dart
  lib/main.dart
  pubspec.yaml
Labels: :star: feat
